version: '3.9'

services:

  frontend:
    container_name: meu-egresso-frontend
    image: meu-egresso-frontend:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8500:80
    restart: always
