version: '3.9'

services:

  mongodb:
    container_name: mongodb-meu-egresso
    image: mongo:6
    restart: unless-stopped
    ports:
      - ${MONGO_EXPOSE_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #volumes:
    #  - ./mongoDB:/data/db

  postgres:
    container_name: postgres-meu-egresso
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    #volumes:
    #   - ./postgresDB:/data/postgres
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    restart: unless-stopped

  backend:
    container_name: meu-egresso-api-homol
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: meu-egresso-api:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - mongodb
      - postgres

#volumes:
#  mongo_report:
#    driver: local
