version: '3.9'

services:

  mongodb:
    container_name: mongodb-meu-egresso
    image: mongo:6
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongoDB:/data/db

  postgres:
    container_name: postgres-meu-egresso
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - ./postgresDB:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped

  backend:
    container_name: meu-egresso-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: meu-egresso-api:latest
    ports:
      - ${APP_PORT}:8080
    restart: always
    depends_on:
      - mongodb
      - postgres

volumes:
  mongo_report:
    driver: local