name: Build and Deploy
on:
  push:
    branches:
      - develop
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
        
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run build
        env:
          NODE_ENV: production
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: develop
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
